# T12B model: neutrino masses

The idea is to check the anality expresion for neutrino masses with SPHENO. I will use a benchmark point

### Rotation of no hermitian mass matrices

Hermitian term:
    
$\mathcal{L}_{\text{mas}} = \psi^{\dagger} M \psi$
$\to$
$M_{\text{diag}}=U^{-1}MU$

No hermitian term:
 
$\mathcal{L}_{\text{mas}} = \psi_R^{\dagger} M \psi_L = \psi_1^{\dagger} M \psi_2$
$\to$ $\color{red}{M_{\text{diag}}^2=V^{-1}MM^TV = U^{-1}M^TMU}$


ie. the $V$ and $U$ matricess diagonalize the matrices $MM^T$ and $M^TM$ respectively

such that: $\Psi_1^i=V_{ij}\psi_1^j$ and $\Psi_2^i=U_{ij}\psi_2^j$

In [1]:
import numpy as np
import pandas as pd
import subprocess
import time

%matplotlib inline
import matplotlib.pyplot as plt 

In [2]:
#good plots
plt.rcParams.update({'font.size': 18}) 
#plt.rc('font',size='18')

In [3]:
Gf = 1.16637000E-05
vevSM = 1./np.sqrt(np.sqrt(2.)*Gf)

# Neutrino masses for a benchmark point

In [4]:
#!/usr/bin/env python
import pyslha
import pyT12B_LesHouches_generator
import subprocess
import sys
import NEUTRINO2018
import neutrino_analytic3
#import Yukawa_fij

# Benchmark point

In [5]:
L1sm = 1.3e-1 #Warning
L61 = 0.
L62 = 0.
L63 = 0.
L71 = 0.
L72 = 0.
L73 = 0.
mu31 = 1.01e6
mu32 = 2.01e6
mu33 = 1.01e8

MN = np.exp(np.random.uniform(np.log(100.),np.log(200.)))
MPsi = np.exp(np.random.uniform(np.log(200.),np.log(2000.)))
Meta = np.exp(np.random.uniform(np.log(300.),np.log(2000.)))
l1 = np.exp(np.random.uniform(np.log(1.0e+3),np.log(1.0e+6)))
l2 = np.exp(np.random.uniform(np.log(1.0e+3),np.log(1.0e+6)))
y1 = np.exp(np.random.uniform(np.log(1.0e-1),np.log(1.0e-6)))
y2 = np.exp(np.random.uniform(np.log(1.0e-1),np.log(1.0e-6)))

In [6]:
print(y1,y2)

2.75031283839e-06 1.42665811034e-05


 Runing firs time

In [7]:
#Open for the first time
xdict = pyT12B_LesHouches_generator.buildSLHAinFile()

# Modific the LesHouches         
xdict.blocks['MINPAR'].entries[1]='%.6E    # lambda1Input' %L1sm     
xdict.blocks['MINPAR'].entries[2]='%.6E    # lambda61Input' %L61
xdict.blocks['MINPAR'].entries[3]='%.6E    # lambda62Input' %L62
xdict.blocks['MINPAR'].entries[4]='%.6E    # lambda63Input' %L63
xdict.blocks['MINPAR'].entries[5]='%.6E    # lambda71Input' %L71   
xdict.blocks['MINPAR'].entries[6]='%.6E    # lambda72Input' %L72   
xdict.blocks['MINPAR'].entries[7]='%.6E    # lambda73Input' %L73       
xdict.blocks['MINPAR'].entries[8]='%.6E    # mu31Input' %mu31
xdict.blocks['MINPAR'].entries[9]='%.6E    # mu32Input' %mu32
xdict.blocks['MINPAR'].entries[10]='%.6E    # mu33Input' %mu33

xdict.blocks['MKIN'].entries[1]='%.6E    # MK' %1.0e+6

xdict.blocks['MNIN'].entries[1]='%.6E    # MN' %MN
xdict.blocks['MR1IN'].entries[1]='%.6E    # Mr1' %MPsi
xdict.blocks['MR2IN'].entries[1]='%.6E    # Mr2' %Meta
xdict.blocks['YLR1IN'].entries[1]='%.6E    # YlR1' %l1
xdict.blocks['YLR2IN'].entries[1]='%.6E    # YlR2' %l2
xdict.blocks['YYR1IN'].entries[1]='%.6E    # YyR1' %y1
xdict.blocks['YYR2IN'].entries[1]='%.6E    # YyR2' %y2

#xdict.blocks['SPHENOINPUT'].entries[55]='%.i             # Calculate loop corrected masses' %0

#Write the Leshouches file for the first time
pyslha.writeSLHAFile('LesHouches.in.T12B_low',xdict)    

#run SPheno for the first time
spheno = subprocess.getoutput('../.././SPheno-4.0.3/bin/SPhenoT12B LesHouches.in.T12B_low')    
SPheno_output = subprocess.getoutput('cat SPheno.spc.T12B')

#Spheno to one loop???
mmS1 = eval(SPheno_output.split('# Mass spectrum')[1].split()[10])
mmS2 = eval(SPheno_output.split('# Mass spectrum')[1].split()[14])
mmS3 = eval(SPheno_output.split('# Mass spectrum')[1].split()[18])

#Anality to tree level
MS1 = np.sqrt(mu31 + L71*vevSM**2/2.)
MS2 = np.sqrt(mu32 + L72*vevSM**2/2.)
MS3 = np.sqrt(mu33 + L73*vevSM**2/2.)
#print(MS1,MS2,MS3)

mx1 = eval(SPheno_output.split('Fe_3')[1].split()[1])
mx2 = eval(SPheno_output.split('Fe_3')[1].split()[5])
mx3 = eval(SPheno_output.split('Fe_3')[1].split()[9])

U11 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[6])
U12 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[11])
U13 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[16])
U21 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[21])
U22 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[26])
U23 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[31])
U31 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[36])
U32 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[41])
U33 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[46])

V11 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[6])
V12 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[11])
V13 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[16])
V21 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[21])
V22 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[26])
V23 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[31])
V31 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[36])
V32 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[41])
V33 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[46])

L1 = neutrino_analytic3.LAMBDA(mx1, MS1, V21, U11) + neutrino_analytic3.LAMBDA(mx2, MS1, V22, U21) +\
        neutrino_analytic3.LAMBDA(mx3, MS1, V32, U31)

L2 = neutrino_analytic3.LAMBDA(mx1, MS2, V21, U11) + neutrino_analytic3.LAMBDA(mx2, MS2, V22, U21) +\
        neutrino_analytic3.LAMBDA(mx3, MS2, V32, U31) 

L3 = neutrino_analytic3.LAMBDA(mx1, MS3, V21, U11) + neutrino_analytic3.LAMBDA(mx2, MS3, V22, U21) +\
        neutrino_analytic3.LAMBDA(mx3, MS3, V32, U31) 


Linv = np.array([[1./L1 ,0.,0],[0.,1./L2,0.],[0.,0.,1./L3]])

In [8]:
print(mmS1,mmS2,mmS3)
print(MS1,MS2,MS3)
print(mx1,mx2,mx3)

955.807552 1417.50121 10049.8467
1004.98756211 1417.74468788 10049.8756211
111.256 17157.1335 72492.7144


In [9]:
def ran_num():
    
    return np.exp(np.random.uniform(np.log(1.*10**(-4)),np.log(10**(0))))

#H random matrix
def h():
    h = np.array([[ran_num(),ran_num(),ran_num()],
                  [ran_num(),ran_num(),ran_num()],
                  [ran_num(),ran_num(),ran_num()]])
    
    return h

In [10]:
h = h()

In [11]:
h

array([[  1.05836861e-01,   2.13310431e-04,   2.87824998e-01],
       [  7.17679930e-02,   1.03595325e-01,   5.84249351e-02],
       [  6.38272630e-02,   1.33644557e-03,   1.66024001e-03]])

In [12]:
hinv = np.linalg.inv(h)
hinv

array([[ -0.05035887,  -0.20608084,  15.98250944],
       [ -1.93579444,   9.75705349,  -7.76103684],
       [  3.49428561,   0.06854744,  -5.87121733]])

In [13]:
np.dot(h,hinv)

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  5.55111512e-17,   1.00000000e+00,  -1.66533454e-16],
       [  2.86229374e-17,  -7.86046575e-19,   1.00000000e+00]])

In [14]:
#PMNS matrix 2018 to 3\sigma https://arxiv.org/abs/1708.01186

#phases of the PMNS matrix and the R 
phases1 = np.random.uniform(0.,0.0*np.pi,3) # WARNING! They are in zero
delta = phases1[0]
eta1 = phases1[1]
eta2 = phases1[2]

#light neutrino masses (up 3 sigma range) NH (NO)
#mnu1 = 10**((np.log10(2.5e-3)-np.log10(1e-9))*np.random.uniform(0,1)+np.log10(1e-9))*1e-9 
#Zero in this framework
mnu1 = 1.0e-20
mnu2 = np.sqrt(np.random.uniform(7.05e-5,8.14e-5)*1.0e-18+mnu1**2)
mnu3 = np.sqrt(np.random.uniform(2.41e-3,2.60e-3)*1.0e-18+mnu1**2)

#mixing angles (up 3 sigma range) NH
t12 = np.arcsin(np.sqrt(np.random.uniform(0.273,0.379)))
t23 = np.arcsin(np.sqrt(np.random.uniform(0.445,0.599)))
t13 = np.arcsin(np.sqrt(np.random.uniform(0.0196,0.0241)))

#Building PMNS matrix NH
UM12 = np.array([ [np.cos(t12),np.sin(t12),0.], [-np.sin(t12),np.cos(t12),0.], [0.,0.,1.0] ])
UM13 = np.array([ [np.cos(t13),0.,np.sin(t13)], [0.,1.0,0.], [-np.sin(t13),0.,np.cos(t13)] ])
UM23 = np.array([ [1.0,0.,0.], [0.,np.cos(t23),np.sin(t23)], [0.,-np.sin(t23),np.cos(t23)] ])
Uphases = np.array([ [np.exp(eta1*1j),0.,0.], [0.,np.exp(eta2*1j),0.], [0.,0.,1.0] ])
P=np.dot(UM23,np.dot(UM13,np.dot(UM12,Uphases))).real

In [15]:
print("mnu1=",mnu1,"mnu2=",mnu2,"mnu3=",mnu3)
print(P)

mnu1= 1e-20 mnu2= 8.93774765458e-12 mnu3= 5.03522433287e-11
[[ 0.79756022  0.58662021  0.14062159]
 [-0.46852681  0.45555304  0.75693729]
 [ 0.37997412 -0.66958805  0.63817827]]


\begin{align}
f = \sqrt{D}R\sqrt{D}U_{{\rm PMNS}}^T\left(h^{-1}\right)^T\Lambda^{-1}\;,
\end{align}

In [16]:
D = np.array([[np.sqrt(mnu1),0.,0.],
              [0.,np.sqrt(mnu2),0.],[0.,0.,np.sqrt(mnu3)]])
D

array([[  1.00000000e-10,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   2.98960661e-06,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   7.09593146e-06]])

In [17]:
R = np.array([[0.,0.,0.],
                  [0.,1.,0.],
                  [0.,0.,1.]])

In [18]:
f = np.dot(np.dot(np.dot(np.dot(np.dot(D,R),D),np.transpose(P)),np.transpose(hinv)),Linv)
f

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [ -8.28317858e-05,   6.44591564e-05,   4.50974953e-05],
       [  4.32655742e-04,   9.22301409e-05,  -1.35375836e-04]])

In [19]:
#ALGORITM:
f11 = f[0,0]
f21 = f[1,0]
f31 = f[2,0]

f12 = f[0,1]
f22 = f[1,1]
f32 = f[2,1]

f13 = f[0,2]    
f23 = f[1,2]
f33 = f[2,2]

h11 = h[0,0]
h21 = h[1,0]
h31 = h[2,0]

h12 = h[0,1]
h22 = h[1,1]
h32 = h[2,1]

h13 = h[0,2]
h23 = h[1,2]
h33 = h[2,2]

In [20]:
x = []

#Open for the second time
xdict = pyT12B_LesHouches_generator.buildSLHAinFile()

# Modific the LesHouches         
xdict.blocks['MINPAR'].entries[1]='%.6E    # lambda1Input' %L1sm     
xdict.blocks['MINPAR'].entries[2]='%.6E    # lambda61Input' %L61
xdict.blocks['MINPAR'].entries[3]='%.6E    # lambda62Input' %L62
xdict.blocks['MINPAR'].entries[4]='%.6E    # lambda63Input' %L63
xdict.blocks['MINPAR'].entries[5]='%.6E    # lambda71Input' %L71   
xdict.blocks['MINPAR'].entries[6]='%.6E    # lambda72Input' %L72   
xdict.blocks['MINPAR'].entries[7]='%.6E    # lambda73Input' %L73       
xdict.blocks['MINPAR'].entries[8]='%.6E    # mu31Input' %mu31
xdict.blocks['MINPAR'].entries[9]='%.6E    # mu32Input' %mu32
xdict.blocks['MINPAR'].entries[10]='%.6E    # mu33Input' %mu33

xdict.blocks['MKIN'].entries[1]='%.6E    # MK' %1.0e+6

xdict.blocks['MNIN'].entries[1]='%.6E    # MN' %MN
xdict.blocks['MR1IN'].entries[1]='%.6E    # Mr1' %MPsi
xdict.blocks['MR2IN'].entries[1]='%.6E    # Mr2' %Meta
xdict.blocks['YLR1IN'].entries[1]='%.6E    # YlR1' %l1
xdict.blocks['YLR2IN'].entries[1]='%.6E    # YlR2' %l2
xdict.blocks['YYR1IN'].entries[1]='%.6E    # YyR1' %y1
xdict.blocks['YYR2IN'].entries[1]='%.6E    # YyR2' %y2

xdict.blocks['YHR1IN'].entries[1]='%.6E    # YhR1(1)' %h11 
xdict.blocks['YHR1IN'].entries[2]='%.6E    # YhR1(2)' %h21
xdict.blocks['YHR1IN'].entries[3]='%.6E    # YhR1(3)' %h31

xdict.blocks['YHR2IN'].entries[1]='%.6E    # YhR2(1)' %h12 
xdict.blocks['YHR2IN'].entries[2]='%.6E    # YhR2(2)' %h22
xdict.blocks['YHR2IN'].entries[3]='%.6E    # YhR2(3)' %h32

xdict.blocks['YHR3IN'].entries[1]='%.6E    # YhR3(1)' %h13 
xdict.blocks['YHR3IN'].entries[2]='%.6E    # YhR3(2)' %h23
xdict.blocks['YHR3IN'].entries[3]='%.6E    # YhR3(3)' %h33

xdict.blocks['YFR1IN'].entries[1]='%.6E    # YfR1(1)' %f11 
xdict.blocks['YFR1IN'].entries[2]='%.6E    # YfR1(2)' %f21
xdict.blocks['YFR1IN'].entries[3]='%.6E    # YfR1(3)' %f31

xdict.blocks['YFR2IN'].entries[1]='%.6E    # YfR2(1)' %f12 
xdict.blocks['YFR2IN'].entries[2]='%.6E    # YfR2(2)' %f22
xdict.blocks['YFR2IN'].entries[3]='%.6E    # YfR2(3)' %f32

xdict.blocks['YFR3IN'].entries[1]='%.6E    # YfR3(1)' %f13 
xdict.blocks['YFR3IN'].entries[2]='%.6E    # YfR3(2)' %f23
xdict.blocks['YFR3IN'].entries[3]='%.6E    # YfR3(3)' %f33

#Write the Leshouches file for the second time
pyslha.writeSLHAFile('LesHouches.in.T12B_low',xdict)    

#run SPheno for the second time
spheno = subprocess.getoutput('../.././SPheno-4.0.3/bin/SPhenoT12B LesHouches.in.T12B_low')    
SPheno_output = subprocess.getoutput('cat SPheno.spc.T12B')

#Spheno to one loop???
MS1 = eval(SPheno_output.split('# Mass spectrum')[1].split()[10])
MS2 = eval(SPheno_output.split('# Mass spectrum')[1].split()[14])
MS3 = eval(SPheno_output.split('# Mass spectrum')[1].split()[18])

#Anality to tree level
#MS1 = np.sqrt(mu31 + L71*vevSM**2/2.)
#MS2 = np.sqrt(mu32 + L72*vevSM**2/2.)
#MS3 = np.sqrt(mu33 + L73*vevSM**2/2.)

mx1 = eval(SPheno_output.split('Fe_3')[1].split()[1])
mx2 = eval(SPheno_output.split('Fe_3')[1].split()[5])
mx3 = eval(SPheno_output.split('Fe_3')[1].split()[9])

U11 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[6])
U12 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[11])
U13 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[16])
U21 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[21])
U22 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[26])
U23 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[31])
U31 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[36])
U32 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[41])
U33 = eval(SPheno_output.split('Block LNEUTROMIX')[1].split()[46])

V11 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[6])
V12 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[11])
V13 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[16])
V21 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[21])
V22 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[26])
V23 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[31])
V31 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[36])
V32 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[41])
V33 = eval(SPheno_output.split('Block RNEUTROMIX')[1].split()[46])

##++++++++++ Neutrinos +++++++++++++++++++++++++++++++++
if SPheno_output.split('# Fk')[1].split()[1] == "NaN":
    mv1 = 0.
else: 
    mv1 = eval(SPheno_output.split('# Fk')[1].split()[1])           
mv2 = eval(SPheno_output.split('# Fk')[1].split()[5])       
mv3 = eval(SPheno_output.split('# Fk')[1].split()[9])  

x.append([L1,L61,L71,L72,L73,mu31,mu32,mu33,MN,MPsi,Meta,l1,l2,y1,y2,h11,h21,h31,h12,h22,h32,h13,h23,h33,f11,f21,f31,\
          f12,f22,f32,f13,f23,f33,mv1,mv2,mv3,MS1,MS2,MS3,mx1,mx2,mx3,V11,V12,V13,V21,V22,V23,V31,V32,V33,\
          U11,U12,U13,U21,U22,U23,U31,U32,U33])

x=np.asarray(x)
    
xd=pd.DataFrame(x,columns=['L1','L61','L71','L72','L73','mu31','mu32','mu33','MN','MPsi','Meta','l1','l2','y1','y2',\
                           'h11','h21','h31','h12','h22','h32','h13','h23','h33','f11','f21','f31','f12','f22',\
                           'f32','f13','f23','f33','mv1','mv2','mv3','MS1','MS2','MS3','mx1','mx2','mx3',\
                           'V11','V12','V13','V21','V22','V23','V31','V32','V33','U11','U12','U13','U21',\
                           'U22','U23','U31','U32','U33'])       

In [21]:
print("EXPERIMENTAL:")
print("mnu2=",mnu2,"mnu3=",mnu3)
print("===============================================")
print("SPHENO:")
print("mv2=",mv2,"mv3=",mv3)
print("===============================================")

EXPERIMENTAL:
mnu2= 8.93774765458e-12 mnu3= 5.03522433287e-11
SPHENO:
mv2= 3.43353371e-12 mv3= 2.80921495e-11


In [22]:
#Factor
print(mnu2/mv2,mnu3/mv3)

2.60307555116 1.79239553487


In [23]:
xd.MS1[0]

0.0

In [24]:
#run anality
MM = neutrino_analytic3.MATRIX_NU_DIAG(xd.h11[0],xd.h12[0],xd.h13[0],xd.h21[0],xd.h22[0],xd.h23[0],xd.h31[0],xd.h32[0],xd.h33[0],\
                    xd.f11[0],xd.f12[0],xd.f13[0],xd.f21[0],xd.f22[0],xd.f23[0],xd.f31[0],xd.f32[0],xd.f33[0],\
                    xd.MS1[0],xd.MS2[0],xd.MS3[0],xd.mx1[0],xd.mx2[0],xd.mx3[0],xd.V12[0],xd.V22[0],xd.V32[0],\
                    xd.U11[0],xd.U21[0],xd.U31[0])

/home/anferivera/Work/Documents_compartidos/T12B/neutrino_analytic3.py:15: RuntimeWarning: divide by zero encountered in log
  Lji = 1./(16.*np.pi**2)*Vj2*Uj1*mj*( (mj**2*np.log(mj**2) - mSi**2*np.log(mSi**2))/(mj**2-mSi**2))
/home/anferivera/Work/Documents_compartidos/T12B/neutrino_analytic3.py:15: RuntimeWarning: invalid value encountered in double_scalars
  Lji = 1./(16.*np.pi**2)*Vj2*Uj1*mj*( (mj**2*np.log(mj**2) - mSi**2*np.log(mSi**2))/(mj**2-mSi**2))


LinAlgError: Array must not contain infs or NaNs

In [ ]:
print("EXPERIMENTAL:")
print("mnu2=",mnu2,"mnu3=",mnu3)
print("===============================================")
print("SPHENO:")
print("mv2=",mv2,"mv3=",mv3)
print("===============================================")
print("ANALITY:")
print("mv2=",MM[1],"mv3=",MM[2])
print("===============================================")

In [ ]:
'''
EXPERIMENTAL:
mnu2= 8.44971790744e-12 mnu3= 4.98108182187e-11
===============================================
SPHENO:
mv2= 8.30927309e-12 mv3= 4.86264552e-11
===============================================
ANALITY:
mv2= 8.62170236709e-12 mv3= 4.91520332098e-11
'''

In [ ]:
'''
EXPERIMENTAL:
mnu2= 8.41504335803e-12 mnu3= 5.07529500712e-11
===============================================
SPHENO:
mv2= 8.28472095e-12 mv3= 5.00036813e-11
===============================================
ANALITY:
mv2= 8.43438103309e-12 mv3= 5.08279154152e-11
===============================================
'''

In [ ]:
'''
EXPERIMENTAL:
mnu2= 8.93576901978e-12 mnu3= 4.97574625124e-11
===============================================
SPHENO:
mv2= 9.07768608e-12 mv3= 5.09852798e-11
===============================================
ANALITY:
mv2= 9.24179733468e-12 mv3= 5.17639661825e-11
===============================================
'''

#### 