# Anality Yukawas

The Yukawa couplings $f_{i\alpha}$ can be written in terms of $h_{i\alpha}$ and the neutrinos observables. For the case of two non-zero neutrino masses we have,

\begin{align}
f = \sqrt{D}R\sqrt{D}U_{{\rm PMNS}}^T\left(h^{-1}\right)^T\Lambda^{-1}\;,
\end{align}

where,

\begin{align}
    R = \left\{ \begin{array}{lcc}
\begin{pmatrix}
0&0&0\\
0&1&0\\
0&0&1
\end{pmatrix} &   {\mathrm{for}}  & {\mathrm{NH}}  \;,
\\ \\ \begin{pmatrix}
1&0&0\\
0&1&0\\
0&0&0
\end{pmatrix} &   {\mathrm{for}}   & {\mathrm{IH}} \;,
\end{array}
\right.
\end{align}

and 

\begin{align}
\sqrt{D} = \left\{ \begin{array}{lcc}
{\rm diag}(\sqrt{v},\sqrt{m_2},\sqrt{m_3}) &   {\mathrm{for}}  & {\mathrm{NH}}  \,,
\\ {\rm diag}(\sqrt{m_1},\sqrt{m_2},\sqrt{v}) &   {\mathrm{for}}   & {\mathrm{IH}} \,.
\end{array}
\right.
\end{align}

h matrix with $h_{i\alpha} = 0$ does not work.

\begin{align}
h = 
\begin{pmatrix}
h_{11}&h_{12}&0\\
h_{21}&h_{22}&0\\
h_{31}&h_{32}&0
\end{pmatrix}
\end{align}

In [1]:
import numpy as np
import NEUTRINO2018

In [2]:
def ran_num():
    
    x = np.exp(np.random.uniform(np.log(1.*10**(-4)),np.log(10**(0))))
    
    return x

In [3]:
#Random h and h^{-1} matrix

def ran_num():
    
    x = np.exp(np.random.uniform(np.log(1.*10**(-4)),np.log(10**(0))))
    
    return x

def h():
    h = np.array([[ran_num(),ran_num(),ran_num()],
                  [ran_num(),ran_num(),ran_num()],
                  [ran_num(),ran_num(),ran_num()]])
    
    return h

def h1(h):
    
    #h inverse
    h1 = np.linalg.inv(h)
    return h1

In [5]:
def D(m1,m2,m3):
    x = np.array([[np.sqrt(m1),0.,0.],
                  [0.,np.sqrt(m2),0.],[0.,0.,np.sqrt(m3)]])
    return x

def R_NH():
    x = np.array([[0.,0.,0.],
                  [0.,1.,0.],
                  [0.,0.,1.]])
    return x

def R_IH():
    x = np.array([[1.,0.,0.],
                  [0.,1.,0.],
                  [0.,0.,0.]])
    return x

In [46]:
def exp_val():
    
    k = NEUTRINO2018.NH()
    UPMNS = np.array([[k['U11'],k['U12'],k['U13']],
              [k['U21'],k['U22'],k['U23']],
              [k['U31'],k['U32'],k['U33']]])
    
    D_M = D(k['mnu1'],k['mnu2'],k['mnu3'])
    
    return UPMNS,D_M

In [47]:
A = exp_val()
exp_val()

(array([[ 0.83689526,  0.5279242 ,  0.14457646],
        [-0.44749461,  0.50779792,  0.73613167],
        [ 0.3152061 , -0.68076229,  0.66121692]]),
 array([[  1.00000000e-10,   0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   2.97335931e-06,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00,   7.04680133e-06]]))

\begin{align}
f = \sqrt{D}R\sqrt{D}U_{{\rm PMNS}}^T\left(h^{-1}\right)^T\Lambda^{-1}\;,
\end{align}

In [48]:
hij = h() 
N = exp_val()

f = np.dot(np.dot(np.dot(np.dot(N[1],R_NH()),N[1]),np.transpose(N[0])),np.transpose(h1(hij)))
f

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [ -6.90882287e-12,  -1.38063277e-11,   2.29315122e-11],
       [ -4.90842756e-11,   8.38653877e-11,   2.91660871e-11]])

In [49]:
#Yukawa without Lambda
def yuk_f():
    
    hij = h() 
    N = exp_val()
    fij = np.dot(np.dot(np.dot(np.dot(N[1],R_NH()),N[1]),np.transpose(N[0])),np.transpose(h1(hij)))
    return hij,fij,N

In [51]:
B = yuk_f()

In [52]:
B

(array([[  6.71743297e-03,   4.50474923e-01,   8.38546528e-01],
        [  1.23532158e-03,   6.27686799e-04,   3.07712974e-02],
        [  1.15259094e-04,   4.21262831e-01,   6.57536249e-04]]),
 array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  4.19323758e-09,  -1.46601958e-11,  -2.00119223e-11],
        [  3.71841254e-08,   7.25954941e-11,  -3.28323771e-10]]),
 (array([[ 0.82429883,  0.54798596,  0.14227727],
         [-0.46983194,  0.52188466,  0.71196513],
         [ 0.31589457, -0.65371843,  0.68765022]]),
  array([[  1.00000000e-10,   0.00000000e+00,   0.00000000e+00],
         [  0.00000000e+00,   2.95431652e-06,   0.00000000e+00],
         [  0.00000000e+00,   0.00000000e+00,   7.09869512e-06]])))

In [61]:
B[2][1]

array([[  1.00000000e-10,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   2.95431652e-06,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   7.09869512e-06]])